version: "3.8"
services:
  cache-master:
    image: "redis:6.0.16"
    container_name: "${HOST_CACHE_MASTER}"
    hostname: "${HOST_CACHE_MASTER}"
    networks:
      - proxy-net
  control-db:
    image: "mongo"
    restart: always
    hostname: "${HOST_CONTROL_DB}"
    container_name: "${HOST_CONTROL_DB}"
    ports:
      - "27017:27017"
    networks:
      - "proxy-net"
  broker:
    image: "rabbitmq:3"
    hostname: "${HOST_BROKER}"
    container_name: "${HOST_BROKER}"
    networks:
      - proxy-net
  request-worker-1:
    build: ./request-worker
    depends_on:
      - cache-master
    container_name: "request-worker-1"
    hostname: "request-worker-1"
    ports:
      - "8000:80"
    environment:
      - HOST_BROKER=${HOST_BROKER}
      - EXCHANGE_NAME=${EXCHANGE_NAME}
    networks:
      - proxy-net
  control-worker:
    build: ./control-worker
    container_name: "control-worker-1"
    hostname: "control-worker-1"
    environment:
      - HOST_BROKER=${HOST_BROKER}
      - EXCHANGE_NAME=${EXCHANGE_NAME}
    depends_on:
      - cache-master
    networks:
      - proxy-net
networks:
  proxy-net:
