version: "3.8"
services:
  master:
    image: "redis:6.0.16"
    container_name: "meli-proxy-redis-master"
    hostname: redis_master
    networks:
      - meli-proxy-net
  worker-node-1:
    build: ./proxy-worker
    depends_on:
      - master
    container_name: "meli-proxy-worker-1"
    hostname: "meli-proxy-worker-1"
    ports:
      - "8000:80"
    networks:
      - meli-proxy-net
  worker-node-2:
    build: ./proxy-worker
    depends_on:
      - master
    container_name: "meli-proxy-worker-2"
    hostname: "meli-proxy-worker-2"
    ports:
      - "8001:80"
    networks:
      - meli-proxy-net
  control-app:
    build: ./control-app
    container_name: "meli-proxy-control-app"
    hostname: "meli-proxy-control-app"
    ports:
      - "8002:80"
    networks:
      - meli-proxy-net
networks:
  meli-proxy-net:
